version: '3'
services:
    #redis-server:
    #    image: 'redis'
    #    ports:
    #        - "6379:6379"
    frontend-server:
        #restart: "no"
        restart: always
        #restart: on-failure 
        environment: 
            - CHOKIDAR_USEPOLLING=true 
        build: 
            context: ./ 
            dockerfile: Dockerfile.dev 
        ports:
            - "3000:3000"
        volumes: 
            - /usr/app/frontend/node_modules 
            - ./:/usr/app/frontend 
    test:
        environment: 
            - CHOKIDAR_USEPOLLING=true 
        build: 
            context: ./ 
            dockerfile: Dockerfile.dev 
        volumes: 
            - /usr/app/frontend/node_modules 
            - ./:/usr/app/frontend 
        command: ["npm", "run", "test"]